const CARDS = [
  { id: 0, 
    img: 'odinbook.gif', 
    github: 'https://github.com/braxtonlemmon/odin-facebook',
    live: 'https://murmuring-wave-95625.herokuapp.com/',
    isLive: true,
    info: {
      title: 'The Odin Book',
      about: 'Social networking project',
      technologies: ['Ruby on Rails', 'HTML', 'CSS'],
    },
  },
  { id: 1, 
    img: 'chess.png', 
    github: 'https://github.com/braxtonlemmon/chess',
    live: '',
    isLive: false,
    info: {
      title: 'Chess',
      about: 'Command line chess game',
      technologies: ['Ruby'],
    },
  },
  { id: 2, 
    img: 'pomodoro.gif', 
    github: 'https://github.com/braxtonlemmon/pomodoro',
    live: 'https://braxtonlemmon.github.io/pomodoro/',
    isLive: true,
    info: {
      title: 'Pomodoro Timer',
      about: 'Productivity tool to manage workflow',
      technologies: ['HTML', 'CSS', 'JavaScript'],
    },
  },
  { id: 3, 
    img: 'weather.png', 
    github: 'https://github.com/braxtonlemmon/weather-app',
    live: 'https://braxtonlemmon.github.io/weather-app/',
    isLive: true,
    info: {
      title: 'Weather Finder',
      about: 'Uses OpenWeather API to obtain live weather data',
      technologies: ['HTML', 'CSS', 'JavaScript', 'React', 'API'],
    },
  },
  { id: 4, 
    img: 'pitchfork.png', 
    github: 'https://github.com/braxtonlemmon/pitchfork-clone',
    live: 'https://braxtonlemmon.github.io/pitchfork-clone/',
    isLive: true,
    info: {
      title: 'Pitchfork Clone',
      about: 'Visual replication of pitchfork.com',
      technologies: ['HTML', 'CSS'],
    },
  },
  { id: 5, 
    img: 'pitchfork.png',
    github: 'https://github.com/braxtonlemmon/pitchfork-clone',
    live: 'https://braxtonlemmon.github.io/pitchfork-clone/',
    isLive: true,
    info: {
      title: 'Pitchfork Clone',
      about: 'Visual replication of pitchfork.com',
      technologies: ['HTML', 'CSS'],
    },
  }
  
];

export default CARDS;